src/models/RequestForm.php
<?php

namespace zhuravljov\yii\rest\models;

use yii\base\Model;
use yii\validators\Validator;

/**
 * Class RequestForm
 *
 * @author Roman Zhuravlev <zhuravljov@gmail.com>
 */
class RequestForm extends Model
{
    public $method;
    public $endpoint;

    public $tab = 1;

    public $queryKeys = [];
    public $queryValues = [];
    public $queryActives = [];

    public $bodyKeys = [];
    public $bodyValues = [];
    public $bodyActives = [];

    public $headerKeys = [];
    public $headerValues = [];
    public $headerActives = [];

    public $description;

    public function rules()
    {
        return [
            ['method', 'required'],
            ['method', 'in', 'range' => array_keys(static::methodLabels())],

            ['endpoint', 'string'],
            ['endpoint', 'validateEndpoint'],

            ['tab', 'in', 'range' => [1, 2, 3]],

            [['queryKeys', 'bodyKeys', 'headerKeys'], 'each', 'rule' => ['string']],
            ['headerKeys', 'each', 'rule' => ['trim']],
            [['queryValues', 'bodyValues', 'headerValues'], 'each', 'rule' => ['string']],
            [['queryActives', 'bodyActives', 'headerActives'], 'each', 'rule' => ['boolean']],

            ['description', 'string'],
        ];
    }

    public function validateEndpoint()
    {
        $url = 'http://example.com/' . $this->endpoint;
        $validator = Validator::createValidator('url', $this, []);
        if ($validator->validate($url, $error)) {
            // Crop fragment
            if (($pos = strpos($this->endpoint, '#')) !== false) {
                $this->endpoint = substr($this->endpoint, 0, $pos);
            }
            // Crop query
            if (($pos = strpos($this->endpoint, '?')) !== false) {
                $this->endpoint = substr($this->endpoint, 0, $pos);
            }
            // Convert query string into params
            $query = trim(parse_url($url, PHP_URL_QUERY));
            $this->parseQuery($query, $this->queryKeys, $this->queryValues, $this->queryActives);
        } else {
            $this->addError('endpoint', $error);
        }
    }

    public function beforeValidate()
    {
        if (parent::beforeValidate()) {
            $this->prepareRows($this->queryKeys, $this->queryValues, $this->queryActives);
            $this->prepareRows($this->bodyKeys, $this->bodyValues, $this->bodyActives);
            $this->prepareRows($this->headerKeys, $this->headerValues, $this->headerActives);

            return true;
        } else {
            return false;
        }
    }

    public function addEmptyRows()
    {
        $this->addEmptyRow($this->queryKeys, $this->queryValues, $this->queryActives);
        $this->addEmptyRow($this->bodyKeys, $this->bodyValues, $this->bodyActives);
        $this->addEmptyRow($this->headerKeys, $this->headerValues, $this->headerActives);
    }

    public function attributeLabels()
    {
        return [
            'endpoint' => 'endpoint',
            'queryKeys' => 'Query Param',
            'queryValues' => 'Value',
            'bodyKeys' => 'Body Param',
            'bodyValues' => 'Value',
            'headerKeys' => 'Header',
            'headerValues' => 'Value',
            'description' => 'Description',
        ];
    }

    public static function methodLabels()
    {
        return [
            'get' => 'GET',
            'post' => 'POST',
            'put' => 'PUT',
            'patch' => 'PATCH',
            'delete' => 'DELETE',
            'head' => 'HEAD',
            'options' => 'OPTIONS',
        ];
    }

    /**
     * @return string
     */
    public function getUri()
    {
        if (($query = $this->getQueryString()) !== '') {
            return  $this->endpoint . '?' . $query;
        } else {
            return  $this->endpoint;
        }
    }

    /**
     * @return string
     */
    public function getQueryString()
    {
        $this->buildQuery($this->queryKeys, $this->queryValues, $this->queryActives, $query);
        return $query;
    }

    /**
     * @return array
     */
    public function getBodyParams()
    {
        $this->buildQuery($this->bodyKeys, $this->bodyValues, $this->bodyActives, $query);
        parse_str($query, $data);

        return $data;
    }

    /**
     * @return array
     */
    public function getHeaders()
    {
        $headers = [];
        foreach ($this->headerKeys as $i => $key) {
            if ($this->headerActives[$i]) {
                $headers[$key][] = $this->headerValues[$i];
            }
        }

        return $headers;
    }

    /**
     * @param string[] $keys
     * @param string[] $values
     * @param boolean[] $actives
     */
    private function prepareRows(&$keys, &$values, &$actives)
    {
        $k = (array)$keys;
        $v = (array)$values;
        $a = (array)$actives;
        $keys = [];
        $values = [];
        $actives = [];
        while(($key = each($k)) && ($value = each($v)) && ($active = each($a))) {
            if ($key[1] !== '' || $value[1] !== '') {
                $keys[] = $key[1];
                $values[] = $value[1];
                $actives[] = $active[1];
            }
        }
    }

    /**
     * @param string[] $keys
     * @param string[] $values
     * @param boolean[] $actives
     */
    private function addEmptyRow(&$keys, &$values, &$actives)
    {
        $keys[] = '';
        $values[] = '';
        $actives[] = true;
    }

    /**
     * @param string $query
     * @param string[] $keys
     * @param string[] $values
     * @param boolean[] $actives
     * @return bool
     */
    private function parseQuery($query, &$keys, &$values, &$actives)
    {
        if ($query !== '') {
            foreach (explode('&', $query) as $couple) {
                list($key, $value) = explode('=', $couple, 2) + [1 => ''];
                $keys[] = urldecode($key);
                $values[] = urldecode($value);
                $actives[] = true;
            }

            return true;
        } else {
            return false;
        }
    }

    /**
     * @param string[] $keys
     * @param string[] $values
     * @param boolean[] $actives
     * @param string $query
     * @return bool
     */
    private function buildQuery($keys, $values, $actives, &$query)
    {
        $couples = [];
        foreach ($keys as $i => $key) {
            if ($actives[$i]) {
                $couples[] =
                    str_replace(['%5B', '%5D'], ['[', ']'], urlencode($key)) .
                    '=' .
                    urlencode($values[$i]);
            }
        }
        $query = join('&', $couples);

        return $query !== '';
    }
}

src/controllers/CollectionController.php
<?php

namespace zhuravljov\yii\rest\controllers;

use Yii;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use zhuravljov\yii\rest\models\ImportForm;

/**
 * Class CollectionController
 *
 * @author Roman Zhuravlev <zhuravljov@gmail.com>
 */
class CollectionController extends Controller
{
    /**
     * @var \zhuravljov\yii\rest\Module
     */
    public $module;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'link' => ['post'],
                    'unlink' => ['post'],
                ],
            ],
        ];
    }

    public function actionLink($tag)
    {
        if ($this->module->storage->addToCollection($tag)) {
            Yii::$app->session->setFlash('success', 'Request was added to collection successfully.');
            return $this->redirect(['request/create', 'tag' => $tag]);
        } else {
            throw new NotFoundHttpException('Request not found.');
        }
    }

    public function actionUnlink($tag)
    {
        if ($this->module->storage->removeFromCollection($tag)) {
            Yii::$app->session->setFlash('success', 'Request was removed from collection successfully.');
            return $this->redirect(['request/create']);
        } else {
            throw new NotFoundHttpException('Request not found.');
        }
    }

    public function actionExport()
    {
        return Yii::$app->response->sendContentAsFile(
            Json::encode($this->module->storage->exportCollection()),
            $this->module->id .'-' . date('Ymd-His') . '.json'
        );
    }

    public function actionImport()
    {
        $model = new ImportForm();
        if (
            $model->load(Yii::$app->request->post()) &&
            ($count = $model->save($this->module->storage)) !== false
        ) {
            if ($count) {
                Yii::$app->session->setFlash('success', "{$count} requests was imported to collection successfully.");
            } else {
                Yii::$app->session->setFlash('warning', "New requests not found.");
            }
            return $this->redirect(['request/create']);
        }
        return $this->render('import', [
            'model' => $model,
        ]);
    }
}

src/controllers/HistoryController.php
<?php

namespace zhuravljov\yii\rest\controllers;

use Yii;
use yii\filters\VerbFilter;
use yii\web\Controller;
use yii\web\NotFoundHttpException;

/**
 * Class HistoryController
 *
 * @author Roman Zhuravlev <zhuravljov@gmail.com>
 */
class HistoryController extends Controller
{
    /**
     * @var \zhuravljov\yii\rest\Module
     */
    public $module;

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post'],
                    'clear' => ['post'],
                ],
            ],
        ];
    }
    public function actionDelete($tag)
    {
        if ($this->module->storage->removeFromHistory($tag)) {
            Yii::$app->session->setFlash('success', 'Request was removed from history successfully.');
            return $this->redirect(['request/create']);
        } else {
            throw new NotFoundHttpException('Request not found.');
        }
    }

    public function actionClear()
    {
        if ($count = $this->module->storage->clearHistory()) {
            Yii::$app->session->setFlash('success', 'History was cleared successfully.');
        } else {
            Yii::$app->session->setFlash('warning', 'History already is empty.');
        }
        return $this->redirect(['request/create']);
    }
}

src/controllers/RequestController.php
<?php

namespace zhuravljov\yii\rest\controllers;

use Yii;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use zhuravljov\yii\rest\helpers\ArrayHelper;
use zhuravljov\yii\rest\models\RequestEvent;
use zhuravljov\yii\rest\models\RequestForm;
use zhuravljov\yii\rest\models\ResponseEvent;
use zhuravljov\yii\rest\models\ResponseRecord;
use zhuravljov\yii\rest\Module;

/**
 * Class RequestController
 *
 * @author Roman Zhuravlev <zhuravljov@gmail.com>
 */
class RequestController extends Controller
{
    /**
     * @var \zhuravljov\yii\rest\Module
     */
    public $module;
    /**
     * @inheritdoc
     */
    public $defaultAction = 'create';

    public function actionCreate($tag = null)
    {
        /** @var RequestForm $model */
        $model = Yii::createObject(RequestForm::className());
        $record = new ResponseRecord();

        if (
            $tag !== null &&
            !$this->module->storage->load($tag, $model, $record)
        ) {
            throw new NotFoundHttpException('Request not found.');
        }

        if (
            $model->load(Yii::$app->request->post()) &&
            $model->validate()
        ) {
            $record = $this->send($model);
            $tag = $this->module->storage->save($model, $record);

            return $this->redirect(['create', 'tag' => $tag, '#' => 'response']);
        }

        $model->addEmptyRows();
        $history = $this->module->storage->getHistory();
        $collection = $this->module->storage->getCollection();

        foreach ($history as $_tag => &$item) {
            $item['in_collection'] = isset($collection[$_tag]);
        }
        unset($item);
        // TODO Grouping will move to the config level
        $collection = ArrayHelper::group($collection, function ($row) {
            if (preg_match('|[^/]+|', ltrim($row['endpoint'], '/'), $m)) {
                return $m[0];
            } else {
                return 'common';
            }
        });

        return $this->render('create', [
            'tag' => $tag,
            'baseUrl' => rtrim($this->module->baseUrl, '/') . '/',
            'model' => $model,
            'record' => $record,
            'history' => $history,
            'collection' => $collection,
        ]);
    }

    /**
     * @param RequestForm $model
     * @return ResponseRecord
     */
    protected function send(RequestForm $model)
    {
        $this->module->trigger(Module::EVENT_ON_REQUEST, new RequestEvent([
            'form' => $model,
        ]));

        /** @var \yii\httpclient\Client $client */
        $client = Yii::createObject($this->module->clientConfig);
        $client->baseUrl = $this->module->baseUrl;

        $begin = microtime(true);
        $response = $client->createRequest()
            ->setMethod($model->method)
            ->setUrl($model->getUri())
            ->setData($model->getBodyParams())
            ->setHeaders($model->getHeaders())
            ->send();
        $duration = microtime(true) - $begin;

        $record = new ResponseRecord();
        $record->status = $response->getStatusCode();
        $record->duration = $duration;
        foreach ($response->getHeaders() as $name => $values) {
            $name = str_replace(' ', '-', ucwords(str_replace('-', ' ', $name)));
            $record->headers[$name] = $values;
        }
        $record->content = $response->getContent();

        $this->module->trigger(Module::EVENT_ON_RESPONSE, new ResponseEvent([
            'form' => $model,
            'record' => $record,
        ]));

        return $record;
    }
}

src/views/request/_collection.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var \yii\web\View $this
 * @var string $activeTag
 * @var array $items
 */
?>
<div class="rest-request-collection">
    <ul id="collection-list" class="request-list">
        <?php foreach ($items as $group => $rows): ?>
            <li>
                <div class="request-list-group">
                    <?= Html::encode($group) ?>
                    <?= Html::tag('span', count($rows), ['class' => 'counter']) ?>
                </div>
                <ul>
                    <?php foreach ($rows as $tag => $row): ?>
                        <?php
                        $options = ['data-tag' => $tag];

                        if ($row['status'] < 300) {
                            Html::addCssClass($options, 'success');
                        } elseif ($row['status'] < 400) {
                            Html::addCssClass($options, 'info');
                        } elseif ($row['status'] < 500) {
                            Html::addCssClass($options, 'warning');
                        } else {
                            Html::addCssClass($options, 'danger');
                        }

                        if ($tag === $activeTag) {
                            Html::addCssClass($options, 'active');
                        }
                        ?>
                        <li <?= Html::renderTagAttributes($options) ?>>
                            <a href="<?= Url::to(['request/create', 'tag' => $tag]) ?>">
                                <span class="request-name">
                                    <span class="request-method">
                                        <?= Html::encode($row['method']) ?>
                                    </span>
                                    <span class="request-endpoint">
                                        <?= Html::encode($row['endpoint']) ?>
                                    </span>
                                </span>
                                <?php if (!empty($row['description'])): ?>
                                    <span class="request-description">
                                        <?= Html::encode($row['description']) ?>
                                    </span>
                                <?php endif; ?>
                            </a>
                            <div class="actions">
                                <?= Html::a('&times;', ['collection/unlink', 'tag' => $tag], [
                                    'data-method' => 'post',
                                    'title' => 'Unlink from collection.',
                                ]) ?>
                            </div>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </li>
        <?php endforeach; ?>
    </ul>

    <div class="well">
        <?php if ($items): ?>
            <?= Html::a('Export Collection', ['collection/export'], [
                'class' => 'btn btn-block btn-default',
                'title' => 'Export collection to file.'
            ]) ?>
        <?php endif; ?>
        <?= Html::a('Import Collection', ['collection/import'], [
            'class' => 'btn btn-block btn-default',
            'title' => 'Import collection from file.'
        ]) ?>
    </div>
</div>

src/views/request/_form-endpoint.php
<?php
/**
 * @var \yii\web\View $this
 * @var string $baseUrl
 */

use yii\helpers\Html;
?>
{label}
<div class="input-group endpoint">
    <div class="input-group-addon" title="<?= Html::encode($baseUrl) ?>">
        <?= Html::encode($baseUrl) ?>
    </div>
    {input}
    <span class="input-group-btn">
        <button class="btn btn-lg btn-primary" type="submit" tabindex="-1">Send</button>
    </span>
</div>
{hint}
{error}
<?php
$this->registerCss(<<<'CSS'

.endpoint > .input-group-addon {
    max-width: 400px;
    overflow: hidden;
    text-overflow: ellipsis;
    font-size: 16px;
}

CSS
);

src/views/request/_form.php
<?php
use yii\bootstrap\ActiveForm;
use yii\helpers\Html;
use zhuravljov\yii\rest\models\RequestForm;

/**
 * @var \yii\web\View $this
 * @var string $baseUrl
 * @var RequestForm $model
 * @var ActiveForm $form
 */
?>
<div class="rest-request-form">
    <?php $form = ActiveForm::begin([
        'action' => ['create'],
        'fieldConfig' => [
            'labelOptions' => ['class' => 'control-label sr-only'],
        ],
        'enableClientValidation' => false,
    ]) ?>
        <?= $form->field($model, 'tab', [
            'template' => '{input}',
            'options' => ['class' => ''],
        ])->hiddenInput() ?>

        <div class="row">
            <div class="col-sm-2">

                <?= $form->field($model, 'method', [
                    'options' => ['class' => 'form-group form-group-lg'],
                ])->dropDownList(RequestForm::methodLabels()) ?>

            </div>
            <div class="col-sm-10">

                <?= $form->field($model, 'endpoint', [
                    'template' => $this->render('_form-endpoint', ['baseUrl' => $baseUrl]),
                    'options' => ['class' => 'form-group form-group-lg'],
                ])->textInput([
                    'placeholder' => 'endpoint',
                    'autofocus' => true,
                ]) ?>

            </div>
        </div>

        <?= $form->field($model, 'description', [
            'options' => [
                'class' => 'form-group form-group-sm',
            ],
        ])->textarea([
            'placeholder' => 'This is description of the request. It show in collection and history.',
            'rows' => 1,
        ]) ?>

        <ul class="nav nav-tabs">
            <?php
            $queryCount = count($model->queryKeys) - 1;
            $bodyCount = count($model->bodyKeys) - 1;
            $headersCount = count($model->headerKeys) - 1;
            ?>
            <li class="<?= $model->tab == 1 ? 'active' : '' ?>">
                <a href="#request-query" data-toggle="tab" tabindex="-1">
                    Query
                    <?= Html::tag('span', $queryCount, [
                        'class' => 'counter' . (!$queryCount ? ' hidden' : '')
                    ]) ?>
                </a>
            </li>
            <li class="<?= $model->tab == 2 ? 'active' : '' ?>">
                <a href="#request-body" data-toggle="tab" tabindex="-1">
                    Body
                    <?= Html::tag('span', $bodyCount, [
                        'class' => 'counter' . (!$bodyCount ? ' hidden' : '')
                    ]) ?>
                </a>
            </li>
            <li class="<?= $model->tab == 3 ? 'active' : '' ?>">
                <a href="#request-headers" data-toggle="tab" tabindex="-1">
                    Headers
                    <?= Html::tag('span', $headersCount, [
                        'class' => 'counter' . (!$headersCount ? ' hidden' : '')
                    ]) ?>
                </a>
            </li>
        </ul>

        <div class="tab-content">

            <div id="request-query" class="tab-pane <?= $model->tab == 1 ? 'active' : '' ?>">
                <?= $this->render('_params', [
                    'model' => $model,
                    'form' => $form,
                    'keyAttribute' => 'queryKeys',
                    'valueAttribute' => 'queryValues',
                    'activeAttribute' => 'queryActives',
                ]) ?>
            </div><!-- #request-params -->

            <div id="request-body" class="tab-pane <?= $model->tab == 2 ? 'active' : '' ?>">
                <?= $this->render('_params', [
                    'model' => $model,
                    'form' => $form,
                    'keyAttribute' => 'bodyKeys',
                    'valueAttribute' => 'bodyValues',
                    'activeAttribute' => 'bodyActives',
                ]) ?>
            </div><!-- #request-body -->

            <div id="request-headers" class="tab-pane <?= $model->tab == 3 ? 'active' : '' ?>">
                <?= $this->render('_params', [
                    'model' => $model,
                    'form' => $form,
                    'keyAttribute' => 'headerKeys',
                    'valueAttribute' => 'headerValues',
                    'activeAttribute' => 'headerActives',
                ]) ?>
            </div><!-- #request-headers -->
        </div>

    <?php ActiveForm::end() ?>
</div>
<?php
$this->registerJs(<<<'JS'

var inputSenderTab = $('#requestform-tab');
$('a[href="#request-query"]').on('shown.bs.tab', function() {
    inputSenderTab.val(1);
    $('#request-query').find(':text').first().focus();
});
$('a[href="#request-body"]').on('shown.bs.tab', function() {
    inputSenderTab.val(2);
    $('#request-body').find(':text').first().focus();
});
$('a[href="#request-headers"]').on('shown.bs.tab', function() {
    inputSenderTab.val(3);
    $('#request-headers').find(':text').first().focus();
});

JS
);

src/views/request/_history.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;

/**
 * @var \yii\web\View $this
 * @var string $activeTag
 * @var array $items
 */
?>
<div class="rest-request-history">

    <ul id="history-list" class="request-list">
        <?php foreach (array_reverse($items, true) as $tag => $row): ?>
            <?php
            $options = ['data-tag' => $tag];

            if ($row['status'] < 300) {
                Html::addCssClass($options, 'success');
            } elseif ($row['status'] < 400) {
                Html::addCssClass($options, 'info');
            } elseif ($row['status'] < 500) {
                Html::addCssClass($options, 'warning');
            } else {
                Html::addCssClass($options, 'danger');
            }

            if ($tag === $activeTag) {
                Html::addCssClass($options, 'active');
            }
            ?>
            <li <?= Html::renderTagAttributes($options) ?>>
                <a href="<?= Url::to(['request/create', 'tag' => $tag]) ?>">
                    <span class="request-name">
                        <span class="request-method">
                            <?= Html::encode($row['method']) ?>
                        </span>
                        <span class="request-endpoint">
                            <?= Html::encode($row['endpoint']) ?>
                        </span>
                    </span>
                    <?php if (!empty($row['description'])): ?>
                        <span class="request-description">
                            <?= Html::encode($row['description']) ?>
                        </span>
                    <?php endif; ?>
                </a>
                <div class="actions">
                    <?php if (!$row['in_collection']): ?>
                        <?= Html::a('&plus;', ['collection/link', 'tag' => $tag], [
                            'data-method' => 'post',
                            'title' => 'Move to collection.',
                        ]) ?>
                    <?php endif; ?>
                    <?= Html::a('&times;', ['history/delete', 'tag' => $tag], [
                        'data-method' => 'post',
                        'title' => 'Remove from history.',
                    ]) ?>
                </div>
            </li>
        <?php endforeach; ?>
    </ul>

    <?php if ($items): ?>
        <div class="well">
            <?= Html::a('Clear History', ['history/clear'], [
                'data' => ['method' => 'post', 'confirm' => 'Are you sure?'],
                'class' => 'btn btn-block btn-danger',
                'title' => 'Full clear history.'
            ]) ?>
        </div>
    <?php endif; ?>
</div>

src/views/request/_params.php
<?php
/**
 * @var \yii\web\View $this
 * @var \yii\base\Model $model
 * @var \yii\widgets\ActiveForm $form
 * @var string $keyAttribute
 * @var string $valueAttribute
 * @var string $activeAttribute
 */
$id = uniqid('params-');
$fieldOptions = [
    'options' => ['class' => 'form-group form-group-sm'],
];
$i = 1;
?>
<div id="<?= $id ?>" class="params-list">
    <table class="table">
        <tbody>
            <?php foreach (array_keys($model->$keyAttribute) as $i): ?>
            <tr data-index="<?= $i ?>">
                <td class="column-check">
                    <?= $form->field($model, $activeAttribute . "[$i]")->checkbox(['tabindex' => -1], false) ?>
                </td>
                <td class="column-key">
                    <?= $form->field($model, $keyAttribute . "[$i]", $fieldOptions)->textInput([
                        'placeholder' => $model->getAttributeLabel($keyAttribute),
                    ]) ?>
                </td>
                <td class="column-value">
                    <?= $form->field($model, $valueAttribute . "[$i]", $fieldOptions)->textInput([
                        'placeholder' => $model->getAttributeLabel($valueAttribute),
                    ]) ?>
                </td>
                <td class="column-actions">
                    <button type="button" class="close" tabindex="-1">
                        <span>&times;</span>
                    </button>
                </td>
            </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
</div>
<?php
// Удаление и добавление строк параметров
$this->registerJs(<<<'JS'

$('.params-list')
    .on('focus', 'tr:last input', function() {
        var curRow = $(this).parents('tr').first();
        var i = parseInt(curRow.data('index'));
        var newRow = curRow.clone();
        newRow.attr('data-index', i + 1);
        newRow.find('input').each(function(){
            $(this).attr('name', $(this).attr('name').replace(
                '[' + i + ']',
                '[' + (i + 1) + ']'
            ));
        });
        newRow.insertAfter(curRow);
        updateCounter($(this).parents('.tab-pane').first());
    })
    .on('click', 'button.close', function() {
        var tab = $(this).parents('.tab-pane').first();
        $(this).parents('tr').remove();
        updateCounter(tab);
    });

function updateCounter(tab) {
    var paramsCount = tab.find('tr').length - 1;
    var tabId = tab.attr('id');
    var counter = $('a[href="#' + tabId + '"] > .counter');
    counter.text(paramsCount);
    if (paramsCount) {
        counter.removeClass('hidden');
    } else {
        counter.addClass('hidden');
    }
}

JS
);
$this->registerCss(<<<'CSS'

.params-list {
    margin: -8px;
}
.params-list .form-group {
    margin-bottom: 0;
}
.params-list .form-group .help-block {
    margin: 0;
}
.params-list td {
    border-top: none !important;
}
.params-list td.column-check,
.params-list td.column-actions {
    width: 30px;
    vertical-align: middle !important;
}
.params-list td.column-key {
    width: 30%;
}
.params-list tr:last-child button.close {
    display: none;
}

CSS
);